### ISSUE TITLE
Exception - A Pipeline Is Already In Use

### ISSUE THREAD

**Issue by shorttp** [TheCloudlessSky/Harbour.RedisSessionStateStore#22]
Hi Adrian,

I deployed Harbour Redis on my site but as soon as another user logs in, or more than one user uses the application, I get the following exception:

Exception type: InvalidOperationException 
    Exception message: A pipeline is already in use
   at ServiceStack.Redis.RedisAllPurposePipeline.Init()
   at ServiceStack.Redis.RedisClient.CreatePipeline()
   at ServiceStack.Redis.Support.Locking.DistributedLock.Lock(String key, Int32 acquisitionTimeout, Int32 lockTimeout, Int64& lockExpire, IRedisClient client)
   at ServiceStack.Redis.Support.Locking.DisposableDistributedLock..ctor(IRedisClient client, String globalLockKey, Int32 acquisitionTimeout, Int32 lockTimeout)
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.GetDistributedLock(IRedisClient client, String key)
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.GetItem(Boolean isExclusive, HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions)
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.GetItemExclusive(HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions)
   at System.Web.SessionState.SessionStateModule.GetSessionStateItem()
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Here is the web.config entry:

<sessionState mode="Custom" customProvider="RedisSessionStateProvider">
      <providers>
        <clear />
        <add name="RedisSessionStateProvider"
             type="Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider" />
      </providers>
    </sessionState>

And here is the global.asax:

            this.clientManager = new PooledRedisClientManager("localhost:6379");
            RedisSessionStateStoreProvider.SetClientManager(this.clientManager);
            RedisSessionStateStoreProvider.SetOptions(new RedisSessionStateStoreOptions()
            {
                KeySeparator = ":",
                OnDistributedLockNotAcquired = sessionId =>
                {
                    Console.WriteLine("Session \"{0}\" could not establish distributed lock. " +
                                      "This most likely means you have to increase the " +
                                      "DistributedLockAcquireSeconds/DistributedLockTimeoutSeconds.", sessionId);
                }
            });

In the web.config, do I need the clientType and host entries?  Is there something silly I am missing?

**Comment by shorttp** [comment]
Hey Adrian,

I know this has been a while, but we finally got around to this issue (had a backlog of items).  It appears the version of Redis we were using was causing the issue.  I switched to the MS OpenTech version and that seemed to solve the issue.
