### ISSUE TITLE
NullReferenceException in ReleaseItemExclusive

### ISSUE THREAD

**Issue by amanda-mitchell** [TheCloudlessSky/Harbour.RedisSessionStateStore#23]
I recently switched from the default session store to `RedisSessionStateStore` on a site that I maintain. Since doing so, I have seen periodic errors logged with the following form:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.ReleaseItemExclusive(HttpContext context, String id, Object lockId) in d:\Repositories\Harbour.RedisSessionStateStore\src\Harbour.RedisSessionStateStore\RedisSessionStateStoreProvider.cs:line 367
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

If the [line number indicated by the stack trace](https://github.com/TheCloudlessSky/Harbour.RedisSessionStateStore/blob/1cd46b3da7e7d442c45e01be8e711877a5d7ac5e/src/Harbour.RedisSessionStateStore/RedisSessionStateStoreProvider.cs#L367) is accurate, the only thing I see that could cause a `NullReferenceException` is the cast of `lockId` to an `int`, although I am not familiar enough with session state stores to know why this would be the case.

**Comment by barankaynak** [comment]
RedisSessionStateStoreProvider line 364
Here Session is null
state.Timeout = context.Session.Timeout;

**Comment by TheCloudlessSky** [comment]
@barankaynak I'm guessing that's because of #26 which was very recently added (but it could be related). How the heck is `Session` null inside of the SessionStateProvider. Anyways, Looks like I'm going to have to check for nulls there and fix it (or if you have a PR I'd be glad to accept it).

**Comment by barankaynak** [comment]
Version 1.3.0 is working very well, but 1.4.0 is giving error. When I put a byte[] array into the session it gives Object reference not set to an instance of an object.

**Comment by ferrt123** [comment]
I have the same problem. On Redis monitor the library execute this:

>1490206496.070684 [0 127.0.0.1:58014] "HGETALL" "RedisSessionStateProvider:iellbpzmnjzoxjzkqfytxhyb"
1490206496.071864 [0 127.0.0.1:58014] "WATCH" "RedisSessionStateProvider:iellbpzmnjzoxjzkqfytxhyb:lock"
1490206496.071927 [0 127.0.0.1:58014] "GET" "RedisSessionStateProvider:iellbpzmnjzoxjzkqfytxhyb:lock"
1490206496.072372 [0 127.0.0.1:58014] "MULTI"
1490206496.072402 [0 127.0.0.1:58014] "DEL" "RedisSessionStateProvider:iellbpzmnjzoxjzkqfytxhyb:lock"
1490206496.072442 [0 127.0.0.1:58014] "EXEC"
1490206496.076770 [0 127.0.0.1:58014] "SETNX" "RedisSessionStateProvider:iellbpzmnjzoxjzkqfytxhyb:lock" "\"\xbf\xd2X\x00\x00\x00\x00"


Sometimes, over and over again
