### ISSUE TITLE
RedisSessionStateStoreProvider.cs not found

### ISSUE THREAD

**Issue by sudaraD** [TheCloudlessSky/Harbour.RedisSessionStateStore#34]
@TheCloudlessSky I am new to this Redis Session store. I have successfully add Redis to my MVC 5 project. but when add new session it gives `RedisSessionStateStoreProvider.cs `not found error. Please help me to solve this.

StackTrace

```
 at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.<>c__DisplayClass7.<ResetItemTimeout>b__5(IRedisClient c) in d:\Repositories\Harbour.RedisSessionStateStore\src\Harbour.RedisSessionStateStore\RedisSessionStateStoreProvider.cs:line 257
   at ServiceStack.Redis.RedisCommandQueue.QueueCommand(Func`2 command, Action`1 onSuccessCallback, Action`1 onErrorCallback)
   at ServiceStack.Redis.RedisCommandQueue.QueueCommand(Func`2 command)
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.<>c__DisplayClass7.<ResetItemTimeout>b__4(IRedisTransaction transaction) in d:\Repositories\Harbour.RedisSessionStateStore\src\Harbour.RedisSessionStateStore\RedisSessionStateStoreProvider.cs:line 257
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.UseTransaction(IRedisClient client, Action`1 action) in d:\Repositories\Harbour.RedisSessionStateStore\src\Harbour.RedisSessionStateStore\RedisSessionStateStoreProvider.cs:line 245
   at Harbour.RedisSessionStateStore.RedisSessionStateStoreProvider.ResetItemTimeout(HttpContext context, String id) in d:\Repositories\Harbour.RedisSessionStateStore\src\Harbour.RedisSessionStateStore\RedisSessionStateStoreProvider.cs:line 255
   at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
```

**Comment by TheCloudlessSky** [comment]
Hey @sudaraD,

Can you provide me with the exctact exception that's being thrown (not just the stack trace? It seems like it's a problem with either your Redis instance (what version is it?) or ServiceStack.Redis (what version is it)?

I also suggest you check out [Microsoft own Redis session state provider](https://msdn.microsoft.com/en-us/library/azure/dn690522.aspx) as I don't really maintain this project since they've released their own version.

**Comment by sudaraD** [comment]
Now its fine. I choose a previous version.
